version: '2.0'
services:
  server:
    image: mysql:5.7
    ports: 
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "mysql"
    networks:
      - mysql 
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "server"
      UPLOAD_LIMIT: 1073741824 # Limit 1GB
    networks:
      - mysql    
networks:
  mysql:
    driver: bridge